# Generated by Django 4.1 on 2022-08-27 05:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.IntegerField()),
                ('status', models.BooleanField()),
                ('question', models.CharField(blank=True, max_length=250)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
