# Generated by Django 4.1 on 2022-08-27 05:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, choices=[('fr', 'Français'), ('ar', 'العربية')], max_length=6, null=True)),
                ('ordered', models.IntegerField()),
                ('status', models.BooleanField()),
                ('question', models.CharField(blank=True, max_length=250)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.faq')),
            ],
        ),
    ]
