# Generated by Django 4.1 on 2022-08-27 05:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_faqlanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqlanguage',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='faqlanguage',
            name='status',
        ),
        migrations.CreateModel(
            name='SettingLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, choices=[('fr', 'Français'), ('ar', 'العربية')], max_length=6, null=True)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('reference', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.setting')),
            ],
        ),
    ]
