# Generated by Django 4.1 on 2022-08-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.BooleanField(),
        ),
    ]
